ALTER TABLE t1 ALTER COLUMN i SET DEFAULT 10
ALTER TABLE t1 ADD COLUMN k INTEGER
ALTER TABLE t1 DROP k
ALTER TABLE t1 ALTER i TYPE VARCHAR
ALTER TABLE t1 ADD PRIMARY KEY (i)
ALTER TABLE t1 RENAME i TO ii
ALTER TABLE t1 RENAME TO t1_old
