ALTER TABLE t1 ALTER COLUMN j SET DEFAULT 'xxx'
ALTER TABLE t1 ADD COLUMN k INTEGER
ALTER TABLE t1 ALTER k TYPE VARCHAR
ALTER TABLE t1 DROP k
ALTER TABLE t1 RENAME j TO jj
ALTER TABLE t1 RENAME TO t1_old

CREATE TABLE t2 (i INTEGER, j varchar)
ALTER TABLE t2 ADD PRIMARY KEY (i, j)
