CREATE SCHEMA s1;
CREATE SCHEMA IF NOT EXISTS s2;


CREATE TABLE s1.t (id INTEGER PRIMARY KEY, other_id INTEGER);
CREATE TABLE s2.t (id INTEGER PRIMARY KEY, j VARCHAR);

describe s1.t;
describe s2.t;
